version: '3'
services:
  jupyter:
    image: pbotapps.azurecr.io/jupyter
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/
    command:
      - start.sh
      - jupyter
      - lab
  sharedstreets:
    image: pbotapps.azurecr.io/sharedstreets-api
    restart: always
